print("VAMOS CALCULAR SUA COMPRA:")
pro_um = input ("Digite o nome do produto 1:")
preco_um = float (input("Digite o preço unitário do produto 1:"))
quant_um = int (input ("Digite a quantidade do produto 1:"))
pro_dois = input ("Digite o nome do produto 2:")
preco_dois = float (input("Digite o preço unitário do produto 2"))
quant_dois = int (input ("Digite a quantidade do produto 2:"))
pro_tres = input ("Digite o nome do produto 3:")
preco_tres = float (input("Digite o preço unitário do produto 3:"))
quant_tres = int (input ("Digite a quantidade do produto 3:"))
total = (quant_um*preco_um)+(quant_dois*preco_dois)+(quant_tres*preco_tres)
print(total)
